security:
  jwt:
    signKey: otherpeopledontknowit!@#
spring:
  h2:
    console.enabled: true
  boot:
    admin:
      client:
        url: "http://localhost:9000"
  datasource:
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop
    url: jdbc:h2:mem:devEnvDb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
