server:
  port: 8081
jwtconfig:
  secret: otherpeopledontknowit

spring:
  boot:
    admin:
      client:
        url: "http://localhost:9000"
  datasource:
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
