server:
  port: 8082
  servlet:
    contextPath: /
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: ${server.servlet.context-path}actuator/health
        health-check-interval: 15s
        health-check-timeout: 90s
        health-check-critical-timeout: 3m
        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

adminProperty: admin`s property value
userProperty: user`s property value
myProperty: my property value